### ISSUE TITLE
requirements.py 出错

### ISSUE THREAD

**Issue by toto222** [7eu7d7/genshin_auto_fish#157]
WARNING: Discarding git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI. Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/philferriere/cocoapi.git 'C:\Users\ttttoooo\AppData\Local\Temp\pip-req-build-zzdm1v0m' Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone --filter=blob:none -q https://github.com/philferriere/cocoapi.git 'C:\Users\ttttoooo\AppData\Local\Temp\pip-req-build-zzdm1v0m' Check the logs for full command output.

**Comment by phcbest** [comment]
> 同requirements.py 出错： Traceback (most recent call last): File "requirements.py", line 74, in main() File "requirements.py", line 68, in main pip_install(args.proxy, line.split() )) 文件“requirements.py”，第 16 行，在 pip_install check=True， 文件“D:\program files\python3.6\lib\subprocess.py”，第 423 行， 与 Popen(*popenargs, ** kwargs) 作为进程： TypeError: **init** () 得到了一个意外的关键字参数 'capture_output'

我也是这个问题，回退版本也没有解决，你解决了吗

**Comment by STRaLxd** [comment]
可以说是解决的，我是因为进入不了github，下载不了环境需要的文件，后来挂了一个梯子解决了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "7eu7d7/genshin_auto_fish"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月1日(星期一) 晚上9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [7eu7d7/genshin_auto_fish] requirements.py 出错 (#157)





  
同requirements.py 出错： Traceback (most recent call last): File "requirements.py", line 74, in main() File "requirements.py", line 68, in main pip_install(args.proxy, line.split() )) 文件“requirements.py”，第 16 行，在 pip_install check=True， 文件“D:\program files\python3.6\lib\subprocess.py”，第 423 行， 与 Popen(*popenargs, ** kwargs) 作为进程： TypeError: init () 得到了一个意外的关键字参数 'capture_output'
  
我也是这个问题，回退版本也没有解决，你解决了吗
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by phcbest** [comment]
> 可以说是解决的，我是因为进入不了github，下载不了环境需要的文件，后来挂了一个梯子解决了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "7eu7d7/genshin_auto_fish" ***@***.***&gt;; 发送时间:&nbsp;2021年11月1日(星期一) 晚上9:55 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [7eu7d7/genshin_auto_fish] requirements.py 出错 (#157) 同requirements.py 出错： Traceback (most recent call last): File "requirements.py", line 74, in main() File "requirements.py", line 68, in main pip_install(args.proxy, line.split() )) 文件“requirements.py”，第 16 行，在 pip_install check=True， 文件“D:\program files\python3.6\lib\subprocess.py”，第 423 行， 与 Popen(*popenargs, ** kwargs) 作为进程： TypeError: init () 得到了一个意外的关键字参数 'capture_output' 我也是这个问题，回退版本也没有解决，你解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我挂的加州的全局，还是没有用-_-

**Comment by Christ101** [comment]
https://github.com/wasabiegg/genshin_auto_fish我下载了这个工程文件，没有报错了

**Comment by phcbest** [comment]
> [https://github.com/wasabiegg/genshin_auto_fish我下载了这个工程文件，没有报错了](https://github.com/wasabiegg/genshin_auto_fish%E6%88%91%E4%B8%8B%E8%BD%BD%E4%BA%86%E8%BF%99%E4%B8%AA%E5%B7%A5%E7%A8%8B%E6%96%87%E4%BB%B6%EF%BC%8C%E6%B2%A1%E6%9C%89%E6%8A%A5%E9%94%99%E4%BA%86)

  receive！
